name: Playwright Tests

on:
  schedule:
    # Каждый день в 06:00 и 15:00 UTC (09:00 и 18:00 МСК)
    - cron: '0 6 * * *'
    - cron: '0 15 * * *'
  workflow_dispatch: # ручной запуск через GitHub UI

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      PROXY_LOGIN: ${{ secrets.PROXY_LOGIN }}
      PROXY_PASS: ${{ secrets.PROXY_PASS }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test tests/prodReg.spec.ts
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
